name: dansho_store
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  connectivity_plus: ^7.3.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  flutter_native_splash: ^2.4.8
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/core/
  fonts:
    #Arabic
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
    #English
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400

  #assets geneator
flutter_assets:
  assets_path: assets/images/core/
  output_path: lib/core/styles/images/
  filename: assets_manager.dart
  field_prefix: null
  #flutter app icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/play_store_512.png"
